name: Implement your github actions steps here

on:
  push:
    branches:
      - main  # Adjust the branch name as needed

jobs:
  sample-student-step:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
